[build]
  command = "npm install && npm run build"
  functions="api"
[[redirects]]
  from = "/*"
  to = "https://jim-issues-tracker-server.netlify.app/.netlify/functions/server/:splat"
  status = 200
  force = true
  signed = "API_SIGNATURE_TOKEN"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]